### ISSUE TITLE
S4 version V3?

### ISSUE THREAD

**Issue by turian** [albertfgu/diffwave-sashimi#7]
The README says:

"The version of S4 used in the experiments in the SaShiMi paper is an outdated version of S4 from January 2022 that predates V2 (February 2022) of the [S4 repository](https://github.com/HazyResearch/state-spaces). S4 is currently on V3 as of July 2022."

Is the latest version of S4 (V3) available in this repo? It was not clear from the README. We would prefer to use the latest.

**Comment by albertfgu** [comment]
It is not available in this repo right now. It is possible to use the V3 version by pasting the standalone file from the S4 repo. However I am not planning to do that because the available checkpoints here were trained on earlier versions of the code. Differences should be relatively minor; it would be possible to port the checkpoints by writing some additional scripts.

**Comment by turian** [comment]
@albertfgu I guess I would be interested in V3 and training checkpoints from scratch

**Comment by albertfgu** [comment]
That would be fantastic! The S4 codebase was actually just updated to v4.0 and won't change in the foreseeable future, so it would be a great time to retrain these models. Unfortunately I don't have any GPUs at the moment, and I don't want to push any code to HEAD here without having the trained models finished.

Updating the implementation is as simple as replacing the S4 file with the updated standalone code: https://github.com/HazyResearch/state-spaces/blob/main/models/s4/s4.py. There are some very small changes:
- The module is now called `S4Block` instead of `S4`. You can resolve this by changing the names everywhere, or even just simply renaming the module in the standalone file.
- IIRC there is a very small discrepancy in the return type of the module; the standalone returns a paper `output, None` while the Sashimi module here might expect just `output`? So you can comment out the second return in the standalone.

Let me know if you have any trouble with this.

**Comment by turian** [comment]
@albertfgu Very interesting. I looked over the changelog but I am curious what you think would be the major differences in using S4 V4 with diffwave sashimi. In particular, how do you think the hyperparams should be updated?

**Comment by albertfgu** [comment]
I think it should be essentially the same as v3 - no hyperparameter changes. Mainly the model design was slightly restructured and substantially cleaned up. If anyone was interested in training a v3 model, they might as well train v4 since the underlying model is the same but the code is more up-to-date.

**Comment by turian** [comment]
@albertfgu Actually, I've been trying the V2 model, as per what the README says when I opened this issue.
If I kill the run would I be able to continue from existing checkpoints using V4? Would there be any training improvements I would see?

**Comment by albertfgu** [comment]
I don't believe that there should be substantial improvements that I can recall.

**Comment by albertfgu** [comment]
Following up on this:

One actual difference with V3/V4 is that the latter support more model variants. In particular the S4D (diagonal) models which are now more popularly used than the original S4. The main advantages of these are (i) a little bit faster (ii) they handle inputs of varying lengths much better, if that comes up in your use case.

**Comment by turian** [comment]
Can you explain more about inputs of varying lengths? For example, I train on 3 seconds of audio but at inference time I can process 6 seconds at a time and see an improvement from the increased context length?

**Comment by albertfgu** [comment]
I wouldn't say you're guaranteed an improvement, but S4D allows you to go back and forth between inputs of different lengths. By "allow" I mean in a computational sense; S4 is "calibrated" to sequences of a certain length. So if you use S4 to repeatedly process inputs of length 3s, 6s, 3s, 6s, it would be inefficient because it will be calibrated to work with 6s inputs and would be computationally slower every time you go back to 3s. For many workflows this isn't a problem (only sequences of 1 length are needed), but if it is then I would recommend S4D. In terms of modeling performance, S4 is probably slightly more reliable and more tested in this setting. I don't expect anything to fail with S4D in this case though.
